### ISSUE TITLE
Issue with seed-phrase

### ISSUE THREAD

**Issue by Maximus3222** [aptos-labs/petra-wallet#9]
Hello, during the work process, I accidentally stumbled upon such an error: when you try to exit the old wallet and then create a new one, the seed phrases during creation and in the account settings differ.

https://user-images.githubusercontent.com/113642692/224576479-fed54867-fbfb-441d-b1f2-9d05355cabec.mov

**Comment by banool** [comment]
Hi, this problem is a known issue with old versions of Petra. I see you're using Petra version 1.0.5. This version is quite out of date, the latest version is 1.1.10, in which this problem is no longer present. We highly encourage you keep Petra up to date to avoid issues like this, which Chrome should generally do automatically (you might want to check your settings!). Thanks for the the report though!
